navigation:
- banner:
    heading: Welcome to Fluidic Colours
    image: images/HomeBanner.png
    message: Explore writings, notes, code, and interactive applications
  file: index.html
  folder: null
  label: Home
- banner:
    heading: Writing & Reflections
    image: images/WritingBanner.jpg
    message: Thoughts, essays, and explorations
  file: writing.html
  folder: Writing
  label: Writing
- banner:
    heading: Notes & Observations
    image: images/NotesBanner.png
    message: Capturing moments of wonder and understanding
  file: notes.html
  folder: Notes
  label: Notes
- banner:
    heading: Code & Development
    image: images/CodingBanner.png
    message: Building tools, solving problems, exploring ideas
  file: coding.html
  folder: Coding
  label: CS and Programming
- banner:
    heading: Resources & Tools
    image: images/ResourcesBanner.png
    message: Curated tools, references, and utilities for learning and building
  file: resources.html
  folder: Resources
  label: Resources
- banner:
    heading: Interactive Apps & Solvers
    image: images/AppsBanner.png
    message: Exploring algorithms through interactive visualizations
  file: apps.html
  folder: Apps
  label: My Apps
- banner:
    heading: Development Journals
    image: images/DevBlogsBanner.png
    message: 'Behind the scenes: building, learning, iterating'
  file: devblogs.html
  folder: Devblogs
  label: Dev Blogs
- banner:
    heading: About Me
    image: images/AboutBanner.png
    message: Join me on this journey of exploration and discovery
  file: about.html
  folder: null
  label: About
site:
  author: Arun Prasaad Gunasekaran
  description: Personal website featuring writings, notes, code, and interactive applications
  dev_mode: false
  email: arunprasaad2711@gmail.com
  title: Fluidic Colours
  url: https://arunprasaad2711.github.io
socials:
- href: https://github.com/arunprasaad2711
  icon: mdi:github
  name: GitHub
- href: https://youtube.com/@fluidiccolours8091
  icon: mdi:youtube
  name: YouTube
- href: mailto:arunprasaad2711@gmail.com
  icon: mdi:email
  name: Email
- href: https://linkedin.com/in/arun-prasaad-gunasekaran-547a59182/
  icon: mdi:linkedin
  name: LinkedIn
- href: https://www.instagram.com/fluidiccolours/
  icon: mdi:instagram
  name: Instagram
- href: https://www.quora.com/profile/Arun-Prasaad-Gunasekaran
  icon: mdi:quora
  name: Quora
themes:
  default: business
  light: cmyk
